#!/bin/sh
NEW_FILES=0
echo "TYPE ALL FILES TO BE COMMITED"
read NEW_FILES
git add $NEW_FILES
NEW_FOLDERS=0
echo "TYPE ALL FOLDERS TO BE COMMITED"
read NEW_FOLDERS
git add $NEW_FOLDERS
COMMIT_M=0
echo "TYPE GIT COMMIT MESSAGE"
read COMMIT_M
git commit -m "$COMMIT_M"
git push
exit 0
